BIN_DIR=bin
OBJ_DIR=obj
SRC_DIR=src
INC_DIR_ROOT=inc

CC=g++
CINC=-I ${INC_DIR_ROOT}/include -I ${INC_DIR_ROOT}/ncurses
CLFLAGS=-lcurses
_CCFLAGS=
CCFLAGS=${_CCFLAGS} ${CLFLAGS}
CCCFLAGS=-c ${_CCFLAGS} ${CINC}

BIN_NAME=MultiShell
BIN_PATH=${BIN_DIR}/${BIN_NAME}

SOURCE_MAIN_CPP=${SRC_DIR}/main.cpp
SOURCEOBJ_MAIN_CPP=${OBJ_DIR}/main.o
HEADER_DEFS_HPP=${INC_DIR_ROOT}/include/defs.hpp
HEADEROBJ_DEFS_HPP=${OBJ_DIR}/defs.o
HEADER_FPS_HPP=${INC_DIR_ROOT}/include/fps.hpp
HEADEROBJ_FPS_HPP=${OBJ_DIR}/fps.o
HEADER_NCURSES_CUSTOM_HPP=${INC_DIR_ROOT}/include/ncurses_custom.hpp
HEADEROBJ_NCURSES_CUSTOM_HPP=${OBJ_DIR}/ncurses_custom.o
HEADER_UTILS_HPP=${INC_DIR_ROOT}/include/utils.hpp
HEADEROBJ_UTILS_HPP=${OBJ_DIR}/utils.o

all: Makefile build

run: Makefile ${BIN_PATH}
	${BIN_PATH}
build: Makefile ${BIN_PATH}


${BIN_PATH}: Makefile ${SOURCEOBJ_MAIN_CPP} ${HEADEROBJ_DEFS_HPP} ${HEADEROBJ_FPS_HPP} ${HEADEROBJ_NCURSES_CUSTOM_HPP} ${HEADEROBJ_UTILS_HPP}
	make dirs
	${CC} \
	${SOURCEOBJ_MAIN_CPP} \
	${HEADEROBJ_DEFS_H} \
	${HEADEROBJ_FPS_H} \
	${CCFLAGS} ${CINC} -o ${BIN_PATH}

${SOURCEOBJ_MAIN_CPP}: ${SOURCE_MAIN_CPP} Makefile
	${CC} ${SOURCE_MAIN_CPP} ${CCCFLAGS} -o ${SOURCEOBJ_MAIN_CPP}
${HEADEROBJ_DEFS_HPP}: ${HEADER_DEFS_HPP} Makefile
	${CC} ${HEADER_DEFS_HPP} ${CCCFLAGS} -o ${HEADEROBJ_DEFS_HPP}
${HEADEROBJ_FPS_HPP}: ${HEADER_FPS_HPP} Makefile
	${CC} ${HEADER_FPS_HPP} ${CCCFLAGS} -o ${HEADEROBJ_FPS_HPP}
${HEADEROBJ_NCURSES_CUSTOM_HPP}: ${HEADER_NCURSES_CUSTOM_HPP} Makefile
	${CC} ${HEADER_NCURSES_CUSTOM_HPP} ${CCCFLAGS} -o ${HEADEROBJ_NCURSES_CUSTOM_HPP}
${HEADEROBJ_UTILS_HPP}: ${HEADER_UTILS_HPP} Makefile
	${CC} ${HEADER_UTILS_HPP} ${CCCFLAGS} -o ${HEADEROBJ_UTILS_HPP}

dirs: Makefile
	mkdir -p ${BIN_DIR} ${OBJ_DIR}
